# This workflow will build a Java project with Gradle and push to GitHub container registry ..  
name: build and push image to github container registry

on:
  push:
    branches: [ main ]

  #Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  reusable-build:
    name: "reusable"
    uses: vishalmamidi/workflows/.github/workflows/gradle-build.yaml@main

  reusable-deploy:
    name: "reusable"
    uses: vishalmamidi/workflows/.github/workflows/aks-deploy.yaml@main