apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.service.namespace }}
  labels:
    app: {{ .Values.service.name }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      name: "{{ .Values.service.port }}"
  selector:
     app: {{ .Values.service.name }}